name: mash_grower_mobile
description: M.A.S.H. Grower Mobile App - Flutter application for mushroom growers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Authentication
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  
  # Networking
  dio: ^5.7.0
  web_socket_channel: ^3.0.1
  connectivity_plus: ^6.0.5
  
  # Firebase
  firebase_messaging: ^15.1.3
  firebase_database: ^11.1.4
  
  # Local Storage
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  
  # UI & Charts
  fl_chart: ^0.69.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.4.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.9
  integration_test:
    sdk: flutter
  
  # Code generation
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
